# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - jetstack/cert-manager
  - jetstack/test-infra
  - jetstack/navigator
  - jetstack/tarmak
  - jetstack/puppet-module-aws_ebs
  - jetstack/puppet-module-calico
  - jetstack/puppet-module-etcd
  - jetstack/puppet-module-kubernetes
  - jetstack/puppet-module-kubernetes_addons
  - jetstack/puppet-module-prometheus
  - jetstack/puppet-module-vault_client
  - jetstack/puppet-module-tarmak
  trusted_org: jetstack

# heart:
#   adorees:
#   - k8s-merge-robot

# slack:
#   mergewarnings:
#   - repos:
#     - kubernetes/kubernetes
#     channels:
#     - kubernetes-dev
#     whitelist:
#     - k8s-merge-robot

milestonestatus:
  # You can curl the following endpoint in order to determine the github ID of your team
  # responsible for maintaining the milestones:
  # curl -H "Authorization: token <token>" https://api.github.com/orgs/<org-name>/teams
  maintainers_id: 2462700

config_updater:
  config_file: prow/config.yaml
  plugin_file: prow/plugins.yaml

plugins:

  jetstack/test-infra:
  - trigger
  - config-updater
  - blunderbuss

  jetstack/cert-manager:
  - docs-no-retest
  - trigger
  - release-note
  - assign
  - close
  - reopen
  - golint
  - heart
  - hold
  - label
  - lgtm
  - milestonestatus
  - size
  - yuks
  - wip
  - shrug

  jetstack/navigator:
  - docs-no-retest
  - trigger
  - release-note
  - assign
  - close
  - reopen
  - golint
  - heart
  - hold
  - label
  - lgtm
  - milestonestatus
  - size
  - yuks
  - wip
  - shrug

  jetstack/tarmak:
  - docs-no-retest
  - trigger
  - release-note
  - assign
  - close
  - reopen
  - golint
  - heart
  - hold
  - label
  - lgtm
  - milestonestatus
  - size
  - yuks
  - wip
  - shrug

  jetstack/puppet-module-aws_ebs:
  - docs-no-retest
  - trigger
  - assign
  - close
  - reopen
  - heart
  - hold
  - label
  - lgtm
  - size
  - yuks
  - wip
  - shrug

  jetstack/puppet-module-calico:
  - docs-no-retest
  - trigger
  - assign
  - close
  - reopen
  - heart
  - hold
  - label
  - lgtm
  - size
  - yuks
  - wip
  - shrug

  jetstack/puppet-module-etcd:
  - docs-no-retest
  - trigger
  - assign
  - close
  - reopen
  - heart
  - hold
  - label
  - lgtm
  - size
  - yuks
  - wip
  - shrug

  jetstack/puppet-module-kubernetes:
  - docs-no-retest
  - trigger
  - assign
  - close
  - reopen
  - heart
  - hold
  - label
  - lgtm
  - size
  - yuks
  - wip
  - shrug

  jetstack/puppet-module-kubernetes_addons:
  - docs-no-retest
  - trigger
  - assign
  - close
  - reopen
  - heart
  - hold
  - label
  - lgtm
  - size
  - yuks
  - wip
  - shrug

  jetstack/puppet-module-prometheus:
  - docs-no-retest
  - trigger
  - assign
  - close
  - reopen
  - heart
  - hold
  - label
  - lgtm
  - size
  - yuks
  - wip
  - shrug

  jetstack/puppet-module-tarmak:
  - docs-no-retest
  - trigger
  - assign
  - close
  - reopen
  - heart
  - hold
  - label
  - lgtm
  - size
  - yuks
  - wip
  - shrug

  jetstack/puppet-module-vault_client:
  - docs-no-retest
  - trigger
  - assign
  - close
  - reopen
  - heart
  - hold
  - label
  - lgtm
  - size
  - yuks
  - wip
  - shrug